### ISSUE TITLE
Error: Cannot find module 'lodash.clonedeep'

### ISSUE THREAD

**Issue by KevCron** [lemavri/kisimyapp#1]
<img width="822" alt="screen shot 2016-04-15 at 7 09 34 pm" src="https://cloud.githubusercontent.com/assets/9090280/14577104/9ea78976-033d-11e6-8eaa-4efcb3bf7e22.png">

Error above when running `node index.html`. Note this happens even after running `npm install`.

Run `npm install --save lodash.clonedeep' to resolve. If you get this error next:

<img width="820" alt="screen shot 2016-04-15 at 7 11 09 pm" src="https://cloud.githubusercontent.com/assets/9090280/14577122/d8e95ac4-033d-11e6-8849-7751abfe9488.png">

Run `npm install --save lodash.omit` to resolve. 

Thank you for the sample, the Kisi docs are not very helpful.

**Comment by mauricioschneider** [comment]
Hey @KevCron, thanks for reporting the issue. I'm glad the sample was useful for you.

**Comment by codemole986** [comment]
Very nice fix. I have googled here and there without success, only THIS solved the issue.
Thanks @KevCron
